# Generated by Django 5.2 on 2025-08-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assingned_to',
            new_name='assigned_to',
        ),
    ]
