# Generated by Django 5.2 on 2025-08-18 10:26

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_initial_users(apps, schema_editor):
    """
    Create a sample Manager and Worker user.
    """

    CustomUser = apps.get_model('users', 'CustomUser')

    # Create Manager user
    manager_user, created = CustomUser.objects.get_or_create(
        email='manager@example.com',
        defaults={
            'username': 'manager',
            'first_name': 'Mirko',
            'last_name': 'Mirkić',
            'role': 'manager',
            'password': make_password('1234'),
            'is_staff': False, # Managers should not have access to the admin site
        }
    )

    # Create a Worker user, assigned to the manager we just created
    CustomUser.objects.get_or_create(
        email='worker@example.com',
        defaults={
            'username': 'worker',
            'first_name': 'Ana',
            'last_name': 'Anić',
            'role': 'worker',
            'manager': manager_user, # Assign the manager
            'password': make_password('1234'),
        }
    )

def remove_initial_users(apps, schema_editor):
    """
    Removes the sample users.
    """
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(
        email__in=['manager@example.com', 'worker@example.com']
    ).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RunPython(create_initial_users, remove_initial_users),
    ]
    